version: "3"
services:
  auth:
    build: ./auth
    ports:
      - "3001:3001"
  event:
    build: ./event
    ports:
      - "3002:3002"
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    ports:
      - "27017:27017"